+incdir+../tb/pkg
+incdir+../tb/sequence_items
+incdir+../tb/env
+incdir+../tb/sequences
+incdir+../tb/drivers
+incdir+../tb/monitors
+incdir+../tb/tests
../tb/pkg/pcie_gen5_6_types_pkg.sv
../tb/interfaces/pcie_pipe_if.sv
../tb/interfaces/pcie_tl_if.sv
../tb/interfaces/pcie_dl_if.sv
../tb/pkg/pcie_gen5_6_pkg.sv
../rtl/pcie_gen5_6_dut_stub.sv
../tb/assertions/pcie_gen5_6_pipe_assertions.sv
../tb/assertions/pcie_gen5_6_tl_assertions.sv
../tb/assertions/pcie_gen5_6_dl_assertions.sv
../tb/assertions/pcie_gen5_6_ltssm_assertions.sv
../tb/top/tb_top.sv
